// data.js
export const peopleData = [
  // ADVENTURE BLOG
  {
    id: 1,
    PersonName: "Mark Twen",
    Avatar: "avatar-male.png",
    PubDate: "Today, 12:00",
    Rating: 3.9,
    Commentary: "This is awesome adventure that I had! Thanks!",
    Topic: "ADVENTURE BLOG",
  },
  {
    id: 2,
    PersonName: "Katherine Johns",
    Avatar: "avatar-female.png",
    PubDate: "5 days ago, 12:15",
    Rating: 4.0,
    Commentary: "The place is very big. I lost the exit.",
    Topic: "ADVENTURE BLOG",
  },
  {
    id: 3,
    PersonName: "Charlie Davis",
    Avatar: "avatar-male.png",
    PubDate: "3 weeks ago, 09:00",
    Rating: 4.7,
    Commentary: "Amazing experience!",
    Topic: "ADVENTURE BLOG",
  },
  {
    id: 4,
    PersonName: "Jack King",
    Avatar: "avatar-male2.png",
    PubDate: "7 months ago, 14:45",
    Rating: 4.3,
    Commentary: "Really good!",
    Topic: "ADVENTURE BLOG",
  },
  {
    id: 5,
    PersonName: "Paul Quinn",
    Avatar: "avatar-male.png",
    PubDate: "1 year ago, 12:00",
    Rating: 4.6,
    Commentary: "Really enjoyed it.",
    Topic: "ADVENTURE BLOG",
  },
  // NATURE BLOG
  {
    id: 6,
    PersonName: "Alice Johnson",
    Avatar: "avatar-female2.png",
    PubDate: "1 week ago, 16:45",
    Rating: 4.8,
    Commentary: "Beautiful scenery and peaceful environment.",
    Topic: "NATURE BLOG",
  },
  {
    id: 7,
    PersonName: "Bob Brown",
    Avatar: "avatar-male2.png",
    PubDate: "2 weeks ago, 10:30",
    Rating: 4.2,
    Commentary: "Great place to relax and unwind.",
    Topic: "NATURE BLOG",
  },
  {
    id: 8,
    PersonName: "Charlie Davis",
    Avatar: "avatar-male.png",
    PubDate: "3 weeks ago, 09:00",
    Rating: 4.5,
    Commentary: "Amazing experience in nature!",
    Topic: "NATURE BLOG",
  },
  {
    id: 9,
    PersonName: "Diana Evans",
    Avatar: "avatar-female.png",
    PubDate: "1 month ago, 13:15",
    Rating: 4.3,
    Commentary: "Loved the natural beauty.",
    Topic: "NATURE BLOG",
  },
  {
    id: 10,
    PersonName: "Eve Foster",
    Avatar: "avatar-female2.png",
    PubDate: "2 months ago, 08:45",
    Rating: 4.0,
    Commentary: "Could be better, but still nice.",
    Topic: "NATURE BLOG",
  },
  // FASHION BLOG
  {
    id: 11,
    PersonName: "Sally Robinson",
    Avatar: "avatar-female2.png",
    PubDate: "Yesterday, 18:30",
    Rating: 4.6,
    Commentary: "Something new for me. Drive and emotions only.",
    Topic: "FASHION BLOG",
  },
  {
    id: 12,
    PersonName: "Diana Evans",
    Avatar: "avatar-female.png",
    PubDate: "1 month ago, 13:15",
    Rating: 4.4,
    Commentary: "Loved the atmosphere.",
    Topic: "FASHION BLOG",
  },
  {
    id: 13,
    PersonName: "Isla Jackson",
    Avatar: "avatar-female2.png",
    PubDate: "6 months ago, 10:15",
    Rating: 4.1,
    Commentary: "Not bad, but not great.",
    Topic: "FASHION BLOG",
  },
  {
    id: 14,
    PersonName: "Olivia Parker",
    Avatar: "avatar-female.png",
    PubDate: "1 year ago, 18:00",
    Rating: 4.7,
    Commentary: "Nice place.",
    Topic: "FASHION BLOG",
  },
  {
    id: 15,
    PersonName: "Sophia Turner",
    Avatar: "avatar-female.png",
    PubDate: "1 year ago, 11:30",
    Rating: 4.9,
    Commentary: "Absolutely fantastic!",
    Topic: "FASHION BLOG",
  },
  // MODERN BLOG
  {
    id: 16,
    PersonName: "Stevie",
    Avatar: "avatar-male2.png",
    PubDate: "2 days ago, 09:05",
    Rating: 3.8,
    Commentary: "Something to be upgraded.",
    Topic: "MODERN BLOG",
  },
  {
    id: 17,
    PersonName: "Eve Foster",
    Avatar: "avatar-female2.png",
    PubDate: "2 months ago, 08:45",
    Rating: 3.9,
    Commentary: "Could be better.",
    Topic: "MODERN BLOG",
  },
  {
    id: 18,
    PersonName: "Noah Owens",
    Avatar: "avatar-male2.png",
    PubDate: "11 months ago, 16:00",
    Rating: 4.0,
    Commentary: "It was okay.",
    Topic: "MODERN BLOG",
  },
  {
    id: 19,
    PersonName: "Henry Irving",
    Avatar: "avatar-male.png",
    PubDate: "5 months ago, 15:00",
    Rating: 4.2,
    Commentary: "Very enjoyable.",
    Topic: "MODERN BLOG",
  },
  {
    id: 20,
    PersonName: "Alice Johnson",
    Avatar: "avatar-female2.png",
    PubDate: "1 week ago, 16:45",
    Rating: 4.1,
    Commentary: "It was okay, not the best.",
    Topic: "MODERN BLOG",
  },
  // SPORT BLOG
  {
    id: 21,
    PersonName: "Jane Smith",
    Avatar: "avatar-female.png",
    PubDate: "4 days ago, 11:00",
    Rating: 4.8,
    Commentary: "Absolutely loved it!",
    Topic: "SPORT BLOG",
  },
  {
    id: 22,
    PersonName: "Frank Green",
    Avatar: "avatar-male2.png",
    PubDate: "3 months ago, 17:30",
    Rating: 4.5,
    Commentary: "Highly recommend!",
    Topic: "SPORT BLOG",
  },
  {
    id: 23,
    PersonName: "Karen Lee",
    Avatar: "avatar-female.png",
    PubDate: "8 months ago, 09:30",
    Rating: 4.6,
    Commentary: "Fantastic!",
    Topic: "SPORT BLOG",
  },
  {
    id: 24,
    PersonName: "Quinn Roberts",
    Avatar: "avatar-female2.png",
    PubDate: "1 year ago, 15:00",
    Rating: 4.3,
    Commentary: "Good experience.",
    Topic: "SPORT BLOG",
  },
  {
    id: 25,
    PersonName: "Grace Harris",
    Avatar: "avatar-female.png",
    PubDate: "4 months ago, 12:00",
    Rating: 4.7,
    Commentary: "Best experience ever!",
    Topic: "SPORT BLOG",
  },
];
